### ISSUE TITLE
User Story 1: Create Magical Maths Monkey Site

### ISSUE THREAD

**Issue by SummonerSkies** [Stephen-Bevan/Magical-Maths-Monkey#19]
As a **student, I want** to have the website, **where I can** practive maths and multiplication in a fun and easy way.

## Acceptance Criteria:
User can reach the website Magical Maths Monkey and practice the maths.
    
## Tasks:

- [X] Create the Magical Maths Monkey with 3 pages.
- [x] Do the proper styling with CSS to make the website easy-to-read.
- [  ]

**Comment by Borys-777** [comment]
As a USER (child), I want to have the website, where I can practive maths and multiplication in a fun and easy way.

**Acceptance Criteria:**
User can reach the website Magical Maths Monkey and practice the maths.

**Tasks:**

Create the Magical Maths Monkey with 3 pages. 
Do the proper styling with CSS to make the website easy-to-read.
